### PR TITLE
remove scan_num, num_lines, trim_space from GuessWidth struct

### PR DESCRIPTION
**Pull request by WindSoilder**
While looking into fields of `GuessWidth`, I don't think we need `scan_num`, `min_lines` and `trim_space` fields in `GuessWidth` struct.
When use it inside nushell, the only one useful field is `header`, and `limit_split` maybe useful.

So I'd propose to make `scan_num, num_lines, trim_space` as a const rather than struct fields.

And this pr also:
1. make some comment into function doc comment
2. move tests from main.rs to guess_width.rs

### CODE REVIEW

**Comment by fdncred** [comment]
I think these are good changes. I had the same idea to decrease the parameters. I'll look a little closer in the morning. Thanks.

**Comment by fdncred** [comment]
After looking at this more, I wonder if MIN_LINES should be a const. I'm not sure but the comments say that it tries to handle multiple blank rows in the body. I know some text programs output blank rows. I'm just not sure. Have you done any testing for those scenarios?

**Comment by WindSoilder** [comment]
I think the meaning of MIN_LINE is we need to set that position only if blank value is larger than MIN_LINE.
Actually I think it has less effects on guessing result, if it doesn't receive too much blank rows.

To be honest, I thik it's rare to define `MIN_LINE` in `detect column` command.  Maybe we can change it back if we need to pass it to `detect column`?

**Comment by fdncred** [comment]
ya, we could change it back if we need it. I'm fine with that. Also, we could do `external | lines | compact | to text | detect columns --guess` if we needed to get rid of blank rows... I think.

Let's go with this for now.

**Pull request merged**
